POST http://localhost:14080/api/sherwood/sarifs
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="sarif"; filename="semgrep.sarif.json"
Content-Type: application/json

< ../sarifs/semgrep.sarif.json
--WebAppBoundary--

###